version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:  
services:
 db:
  image: postgres:9.6
  environment:
   - POSTGRES_HOST_AUTH_METHOD=trust
  volumes:
   - dados:/var/lib/postgresql/data
   - ./scripts:/scripts
   - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
   - 5433:5432
  networks:
    - banco
 frontend:
  image: nginx:1.13
  volumes:
   - ./web:/usr/share/nginx/html
   #Configuração do proxy reverso
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  ports:
   - 80:80 
  networks:
    - web
  depends_on:
    - app
 app:
  image: python:3.6
  volumes:
    - ./app:/app
  working_dir: /app
  command: bash ./app.sh
  networks:
    - banco
    - web
    - fila
  depends_on:
    - db
    - queue
  environment:
    - DB_NAME=abc_sender
 queue:
  image: redis:3.2
  networks:
    - fila
 worker:
  build: worker
  volumes:
    #Mapeia o código .py dentro da pasta "worker" para o diretório "worker" dentro do container docker
    - ./worker:/worker
  working_dir: /worker
  command: worker.py
  networks:
    - fila
  depends_on:
    - queue